AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 300

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - docker/**/*.rb
    - remotus.gemspec
    - lib/remotus/ssh_connection.rb

Metrics/AbcSize:
  Max: 25
  Exclude:
    - lib/remotus/ssh_connection.rb

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/remotus/ssh_connection.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/remotus/ssh_connection.rb

Metrics/PerceivedComplexity:
  Exclude:
    - lib/remotus/ssh_connection.rb

Metrics/ParameterLists:
  Max: 6

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
